
import java.util.Timer;
import java.util.TimerTask;

public class MainScreen extends javax.swing.JFrame {

  public int time = 0;
  public Timer timer = new Timer();
  public ScrambleHandler scrambleHandler = new ScrambleHandler();
  public TimeHandler timeHandler = new TimeHandler();
  
  /**
   * Creates new form MainScreen
   */
  public MainScreen() {
    initComponents();
    lblScramble.setText(scrambleHandler.generateScramble());
    lblTime.setText(timeHandler.getFormatedTime());
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    Timer = new javax.swing.JPanel();
    lblTime = new javax.swing.JLabel();
    divControls = new javax.swing.JPanel();
    btnDnf = new javax.swing.JButton();
    btnToggleTime = new javax.swing.JButton();
    btnPenalty = new javax.swing.JButton();
    btnReset = new javax.swing.JButton();
    divAverages = new javax.swing.JPanel();
    lblAO5 = new javax.swing.JLabel();
    lblAO7 = new javax.swing.JLabel();
    lblScramble = new javax.swing.JLabel();
    Stats = new javax.swing.JPanel();
    Trainer = new javax.swing.JPanel();
    Help = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTabbedPane1.setBackground(new java.awt.Color(0, 0, 255));

    lblTime.setFont(new java.awt.Font("Consolas", 1, 72)); // NOI18N
    lblTime.setText("00:00:00");

    btnDnf.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    btnDnf.setText("DNF");
    btnDnf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDnfActionPerformed(evt);
      }
    });

    btnToggleTime.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    btnToggleTime.setText("START");
    btnToggleTime.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnToggleTimeActionPerformed(evt);
      }
    });

    btnPenalty.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    btnPenalty.setText("+2");
    btnPenalty.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPenaltyActionPerformed(evt);
      }
    });

    btnReset.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    btnReset.setText("RESET");
    btnReset.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnResetActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout divControlsLayout = new javax.swing.GroupLayout(divControls);
    divControls.setLayout(divControlsLayout);
    divControlsLayout.setHorizontalGroup(
        divControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divControlsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPenalty)
                .addGap(18, 18, 18)
                .addGroup(divControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnToggleTime, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnDnf)
                .addGap(19, 19, 19)));
    divControlsLayout.setVerticalGroup(
        divControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divControlsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnToggleTime)
                .addGap(18, 18, 18)
                .addGroup(divControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDnf)
                    .addComponent(btnPenalty)
                    .addComponent(btnReset))));

    lblAO5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    lblAO5.setText("Last 5: 00:00");

    lblAO7.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    lblAO7.setText("Last 7: 00:00");

    javax.swing.GroupLayout divAveragesLayout = new javax.swing.GroupLayout(divAverages);
    divAverages.setLayout(divAveragesLayout);
    divAveragesLayout.setHorizontalGroup(
        divAveragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divAveragesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAO5)
                .addGap(18, 18, 18)
                .addComponent(lblAO7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    divAveragesLayout.setVerticalGroup(
        divAveragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divAveragesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(divAveragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAO5)
                    .addComponent(lblAO7))
                .addGap(38, 38, 38)));

    lblScramble.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    lblScramble.setText("--scramble--error--");

    javax.swing.GroupLayout TimerLayout = new javax.swing.GroupLayout(Timer);
    Timer.setLayout(TimerLayout);
    TimerLayout.setHorizontalGroup(
        TimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimerLayout.createSequentialGroup()
                .addGroup(TimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblScramble, javax.swing.GroupLayout.PREFERRED_SIZE, 854,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TimerLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addGroup(TimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTime)
                            .addGroup(TimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TimerLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(divControls, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(TimerLayout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(divAverages, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(128, Short.MAX_VALUE)));
    TimerLayout.setVerticalGroup(
        TimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimerLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblScramble)
                .addGap(92, 92, 92)
                .addComponent(lblTime)
                .addGap(18, 18, 18)
                .addComponent(divAverages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(divControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE)));

    jTabbedPane1.addTab("Timer", Timer);

    javax.swing.GroupLayout StatsLayout = new javax.swing.GroupLayout(Stats);
    Stats.setLayout(StatsLayout);
    StatsLayout.setHorizontalGroup(
        StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE));
    StatsLayout.setVerticalGroup(
        StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE));

    jTabbedPane1.addTab("Stats", Stats);

    javax.swing.GroupLayout TrainerLayout = new javax.swing.GroupLayout(Trainer);
    Trainer.setLayout(TrainerLayout);
    TrainerLayout.setHorizontalGroup(
        TrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE));
    TrainerLayout.setVerticalGroup(
        TrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE));

    jTabbedPane1.addTab("Trainer", Trainer);

    javax.swing.GroupLayout HelpLayout = new javax.swing.GroupLayout(Help);
    Help.setLayout(HelpLayout);
    HelpLayout.setHorizontalGroup(
        HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE));
    HelpLayout.setVerticalGroup(
        HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE));

    jTabbedPane1.addTab("Help", Help);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public void updateTimer() {
    lblTime.setText(timeHandler.getFormatedTime());
  }

  private void btnToggleTimeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnToggleTimeActionPerformed
    // Toggles count state
    System.out.print("Toggle Triggered \t");
    timeHandler.toggleCountState();

    // Changes button text based on count state
    btnToggleTime.setText(timeHandler.getCountState() ? "STOP" : "START");
    System.out.print("countState: ");
    System.out.println(timeHandler.getCountState());

    // Handles timer functions
    if (timeHandler.getCountState()) {
      // Creates a timer that executes the increment function every 0.01 seconds and
      // refreshes the text displayed on screen
      timer = new Timer();
      timer.schedule(new TimerTask() {
        public void run() {
          timeHandler.incrementTime(10);
          updateTimer();
        }
      }, 10, 10);
    } else {
      // Stops the timer
      timer.cancel();
    }

  }// GEN-LAST:event_btnToggleTimeActionPerformed

  private void btnDnfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDnfActionPerformed
    timeHandler.setTime(0);
  }// GEN-LAST:event_btnDnfActionPerformed

  private void btnPenaltyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPenaltyActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_btnPenaltyActionPerformed

  private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPenalty1ActionPerformed
    System.out.println("Reset triggered");
    // Counstate
    timeHandler.setCountState(false);
    timeHandler.setTime(0);
    timer.cancel();
    updateTimer();

    // Scramble
    lblScramble.setText(scrambleHandler.generateScramble());
  }// GEN-LAST:event_btnPenalty1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainScreen().setVisible(true);
      }
    });

  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Help;
  private javax.swing.JPanel Stats;
  private javax.swing.JPanel Timer;
  private javax.swing.JPanel Trainer;
  private javax.swing.JButton btnDnf;
  private javax.swing.JButton btnPenalty;
  private javax.swing.JButton btnReset;
  private javax.swing.JButton btnToggleTime;
  private javax.swing.JPanel divAverages;
  private javax.swing.JPanel divControls;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JLabel lblAO5;
  private javax.swing.JLabel lblAO7;
  private javax.swing.JLabel lblScramble;
  private javax.swing.JLabel lblTime;
  // End of variables declaration//GEN-END:variables
}
